services:
    api:
        build: .
        ports:
            - "80:8000"
        restart: unless-stopped
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 4
    
    postgres:
        image: postgres:16
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        env_file: ".env"
        ports:
            - "5432:5432"
        networks:
            - app-network
        command: >
            postgres -c max_connections=1000
                -c shared_buffers=256MB
                -c effective_cache_size=768MB
                -c maintenance_work_mem=64MB
                -c checkpoint_completion_target=0.7
                -c wal_buffers=16MB
                -c default_statistics_target=100
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d app" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        tty: true
        stdin_open: true    

networks:
    app-network:
        driver: bridge

volumes:
  pgdata:
    driver: local